channels:
- openbabel
- rdkit
dependencies:
- python==3.9
- numpydoc
- six
- numpy>=1.8
- scipy>=0.14
- scikit-image
- scikit-learn>=0.18
- joblib>=0.8
- pandas>=0.17.1
- xlsxwriter
- rdkit
- openbabel
- pytest
- pytest-xdist