channels:
- conda-forge
dependencies:
- python=3.12
- numpydoc
- numpy>=1.13
- scipy>=0.14
- scikit-image
- scikit-learn>=0.18
- joblib>=0.8
- pandas>=0.17.1
- packaging>=20
- xlsxwriter
- rdkit>=2026.03.1
- openbabel>=3.2.1
- vina>=1.2.7
- pytest
- pytest-xdist
- black